[package]
name = "pddllib"
version = "0.1.2"
edition = "2021"
authors = ["Jan M. D. Hansen"]
license = "GPL-3.0-only"
license-file = "LICENSE"
repository = "https://github.com/jamadaha/pddllib"
description = "A PDDL library for lifted successor generation"

[dependencies]
indexmap = "2.2.3"
itertools = "0.12.1"
pddlp = { version = "0.1.2", optional = true }

[dev-dependencies]
pathfinding = "4.9.1"
criterion = "0.5.1"

[features]
default = ["translation"]
translation = ["dep:pddlp"]

[[bench]]
name = "bench_main"
harness = false
