[package]
name = "pddllib"
version = "0.1.0"
edition = "2021"
authors = ["Jan M. D. Hansen"]
license-file = "LICENSE"
repository = "https://github.com/jamadaha/pddllib"
description = "A PDDL library for lifted successor generation"

[dependencies]
indexmap = "2.2.3"
itertools = "0.12.1"
pddlp = { version = "0.1.2", optional = true }

[features]
default = ["translation"]
translation = ["dep:pddlp"]
